version: '3'

services:
    verification:
        build:
            context: .  # Каталог с Dockerfile
            dockerfile: Dockerfile
        volumes:
            - .:/app
        stop_grace_period: 1s
        working_dir: /app
        user: "1000:1000"
        command:
            - sh
            - -c
            - |
                cd packages/verification; node ../../common/scripts/install-run-rushx.js dev
        ports:
            - 3020:3020
        networks:
            - app-network

    backend:
        image: node:18-alpine
        stop_grace_period: 1s
        volumes:
            - .:/app
        working_dir: /app
        user: '${UID-1000}:${GID-1000}'
        command:
            - sh
            - -c
            - |
                cd packages/backend; node ../../common/scripts/install-run-rushx.js dev
        ports:
            - 3001:3001
        networks:
            - app-network
    api:
        image: node:18-alpine
        stop_grace_period: 1s
        volumes:
            - .:/app
        working_dir: /app
        user: '${UID-1000}:${GID-1000}'
        command:
            - sh
            - -c
            - |
                cd packages/api; node ../../common/scripts/install-run-rushx.js dev
        ports:
            - 3010:3010
        networks:
            - app-network


    mongodb:
        container_name: mongodb
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
            - MONGO_INITDB_DATABASE=site
        volumes:
            - dbdata:/data/db
        ports:
            - '27017:27017'
        networks:
            - app-network

    mongo-express:
        container_name: mongo-express
        image: mongo-express
        restart: always
        depends_on:
            - mongodb
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=admin
            - ME_CONFIG_MONGODB_URL=mongodb://admin:admin@mongodb:27017/
        ports:
            - '8081:8081'
        networks:
            - app-network

    keycloak:
        container_name: keycloak
        image: quay.io/keycloak/keycloak:21.1.1
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
        volumes:
            - ./packages/backend/keycloak/realms:/opt/keycloak/data/import
        ports:
            - '8080:8080'
        command: start-dev --import-realm

        networks:
            - app-network
#    common:
#        build:
#            context: .  # Каталог с Dockerfile
#            dockerfile: Dockerfile
#        volumes:
#            - .:/app
#        stop_grace_period: 1s
#        working_dir: /app
#        user: '${UID-1000}:${GID-1000}'
#        command:
#            - sh
#            - -c
#            - |
#                cd packages/verification; npm run dev
#        ports:
#            - 3020:3020
#        networks:
#            - app-network
networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
    node_modules:
