export const QUERY_KEYS = {
    GET_CURRENT_SOLUTION: '/GET_CURRENT_SOLUTION_QUERY',
    START_SOLUTION: '/START_SOLUTION_QUERY',
    COMMIT: '/COMMIT_QUERY',
    NEW_TRY: '/NEW_TRY_QUERY',
    SWITCH_TRY: '/SWITCH_TRY_QUERY',
    SWITCH_HEAD_FRAME: '/SWITCH_HEAD_FRAME_QUERY',
    LOGIN: '/LOGIN_QUERY'
};

export const QUERY_WITHOUT_AUTH = [QUERY_KEYS.LOGIN];
