export const QUERY_KEYS = {
  SIGN_UP: 'sign-up',
  SIGN_IN: 'sign-in',
  LOGOUT: 'logout',
  ME: 'me',
  SET_DISPLAY_NAME: 'set-display-name',
  SET_FULL_NAME: 'set-full-name',
  GET_NOT_APPROVED_TASKS_LIST: 'get-not-approved-tasks-list',
  GET_CREATED_TASKS_LIST: 'get-created-tasks-list',
  SET_AVATAR: 'set-avatar',
  CREATE_TASK: 'create-task',
  DELETE_TASK: 'delete-task',
  UPDATE_TASK: 'update-task',
  APPROVE_TASK: 'approve-task',
  UPLOAD_TASK_SOURCE: 'upload-task-source',
  SEARCH_USER: 'search-user',
  CHANGE_ROLE: 'change-role',
  START_SOLUTION: 'start-solution',
  SWITCH_HEAD_FRAME: 'switch-head-frame',
  SWITCH_TRY: 'switch-try',
  NEW_TRY: 'new-try',
  COMMIT: 'commit',
  GET_CURRENT_SOLUTION: 'get-current-solution'
};
